GloriousGarden/Controllers/CalendarItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GloriousGarden.Models;

namespace GloriousGarden.Controllers
{
    public class CalendarItemsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        //GET: CalendarItems
        public ActionResult Index()
        {
           return View();
        }
        private static DateTime ConvertFromUnixTimestamp(double timestamp)
        {
            var origin = new DateTime(1970, 1, 1, 0, 0, 0, 0);
            return origin.AddSeconds(timestamp);
        }
        public JsonResult GetDiaryEvents(DateTime start, DateTime end)
        {

            var ApptListForDate = db.CalendarItems.ToList(); 
            var eventList = from e in ApptListForDate
                            where e.EventDate >= start && e.EventDate <=end
                            select new
                            {
                                id = e.ID,
                                title = e.EventAction,
                                start = e.EventDate,
                            };
            var rows = eventList.ToArray();
            return Json(rows, JsonRequestBehavior.AllowGet);
        }

        public Boolean DeleteEvent(int EventID)
        {
            return CalendarItem.DeleteEvent(EventID);
        }
        public Boolean SaveEvent(int EventID,string Title, string EventDate)
        {
            return CalendarItem.EditEvent(EventID, EventDate,Title);
        }
        public Boolean AddEvent(string Title, string NewEventDate)
        {
            return CalendarItem.AddEvent(NewEventDate, Title);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GloriousGarden/Controllers/CropsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace GloriousGarden.Models
{
    public class CropsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Crops
        public ActionResult Index()
        {
            var crops = db.Crops.Include(c => c.Location);
            return View(crops.ToList());
        }

        // GET: Crops/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Crops crops = db.Crops.Find(id);
            if (crops == null)
            {
                return HttpNotFound();
            }
            return View(crops);
        }

        // GET: Crops/Create
        public ActionResult Create()
        {
            ViewBag.LocationIdRef = new SelectList(db.locations, "LocationId", "LocationName");
            return View();
        }

        // POST: Crops/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CropName,Variety,SownDate,PlantedDate,GerminationDate,HarvestDate,LocationIdRef,yield,satisfaction,notes")] Crops crops)
        {
            if (ModelState.IsValid)
            {
                db.Crops.Add(crops);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LocationIdRef = new SelectList(db.locations, "LocationId", "LocationName", crops.LocationIdRef);
            return View(crops);
        }

        // GET: Crops/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Crops crops = db.Crops.Find(id);
            if (crops == null)
            {
                return HttpNotFound();
            }
            ViewBag.LocationIdRef = new SelectList(db.locations, "LocationId", "LocationName", crops.LocationIdRef);
            return View(crops);
        }

        // POST: Crops/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CropName,Variety,SownDate,PlantedDate,GerminationDate,HarvestDate,LocationIdRef,yield,satisfaction,notes")] Crops crops)
        {
            if (ModelState.IsValid)
            {
                db.Entry(crops).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LocationIdRef = new SelectList(db.locations, "LocationId", "LocationName", crops.LocationIdRef);
            return View(crops);
        }

        // GET: Crops/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Crops crops = db.Crops.Find(id);
            if (crops == null)
            {
                return HttpNotFound();
            }
            return View(crops);
        }

        // POST: Crops/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Crops crops = db.Crops.Find(id);
            db.Crops.Remove(crops);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GloriousGarden/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GloriousGarden.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

GloriousGarden/Views/Home/About.cshtml
@{
    ViewBag.Title = "About Alan and Maggie's Glorious Garden";
}
<h2>@ViewBag.Title.</h2>


<p>Alan created this website to learn about the MVC framework, Code First with Entity Framework, Bootstrap and other web skills. Having mainly worked with Windows Forms for the last few years he felt the need to brush up</p>

GloriousGarden/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

GloriousGarden/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-md-4">
        <div div="list-group">
            <div class="list-group-item">
                <img src="~/Content/Images/crops.png" alt="Our Crops" />
                <a href='@Url.Action("Index", "Crops")' class="btn-link" style="text-align:right">Our Crops</a>
            </div>
            <div class="list-group-item">
                <img src="~/Content/Images/acres.png" alt="Our Acres" />

                <a href='@Url.Action("Index","Locations")' class="btn-link" style="text-align:right">Our Acres</a>
            </div>
            <div class="list-group-item">   
                <img src="~/Content/Images/Diary.png" alt="Diary" />  
                <a href='@Url.Action("Index","CalendarItems")' class="btn-link" style="text-align:right">Our Gardening Diary</a>
            </div>
        </div>
    </div>
</div>

@section Scripts {
}